version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mi-php-app
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
volumes:
  memorama-vol:
